name: Archive feature- or bugfix-branch

on:
  workflow_call:
    inputs:
      git-branch:
        required: true
        type: string
  
permissions:
  contents: write

jobs:
  archive-feature-branch:
    if: ${{ (startsWith(inputs.git-branch, 'feature/') || startsWith(inputs.git-branch, 'bugfix/')) && (github.event.pull_request == null || github.event.pull_request.merged || github.event.pull_request.closed) }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.git-branch }}

      - name: Create archive ref
        run: |
          git update-ref "refs/archive/${{ inputs.git-branch }}" "${{ inputs.git-branch }}"
          git push origin "refs/archive/${{ inputs.git-branch }}:refs/archive/${{ inputs.git-branch }}"

      - name: Delete feature branch
        run: git push -d origin "${{ inputs.git-branch }}"