name: Archive feature- or bugfix-branch

on:
  workflow_call:
    inputs:
      git-branch:
        required: true
        type: string
  
permissions:
  contents: write

jobs:
  archive-feature-branch:
    if: ${{ (startsWith(inputs.git-branch, 'feature/') || startsWith(inputs.git-branch, 'bugfix/') || startsWith(inputs.git-branch, 'copilot/')) && (github.event.pull_request == null || github.event.pull_request.merged || github.event.pull_request.closed) }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ inputs.git-branch }}

      - name: Create archive ref
        run: |
          git update-ref "refs/archive/${{ inputs.git-branch }}" "${{ inputs.git-branch }}"
          git push origin "refs/archive/${{ inputs.git-branch }}:refs/archive/${{ inputs.git-branch }}"

      - name: Delete feature branch
        run: git push -d origin "${{ inputs.git-branch }}"